- bu_isciii/drylab_api.py
Write the examples for requesting information to iSkyLIMS using the REST API
> Described the methods used for iSkyLIMs API requests

- templates/services.json
Fixed some typos in the json template.
> Fixed some typos in json template

- .gitignore
- LICENSE
- README.md
- deliver_automatization.json
Deliver automation beginning  script
> deliver automation 

- bu_isciii/__init__.py
- bu_isciii/__main__.py
- bu_isciii/drylab_api.py
- bu_isciii/new_service.py
- bu_isciii/utils.py
- requirements.txt
- setup.py
- tox.ini
Partially Closes #20 , logging is left.
> Chained main.py and modules, first prompt working!!

- bu_isciii/copy_sftp.py
- bu_isciii/schemas/schema_sftp_copy.json
> SFTP copy 

- bu_isciii/drylab_api.py
- bu_isciii/utils.py
Function write_to_log is removed from the utils file.
For logging information we will use the same way as used in nf-core
> Removed write_to_log function in utils.

- bu_isciii/list.py
Pablo and I (with Luis marvellous help) add two methods to list the bu-isciii servicies. I have to change the first part by json_reader from Luis.
> List class move forward

- bu_isciii/__main__.py
- bu_isciii/new_service.py
- bu_isciii/utils.py
- Created prompt for selecting service for copying the template
- Added some try/catch and messages.
- Starting adding more parameters to new_service
> Created prompt for selecting service for copying the template!

- bu_isciii/__main__.py
- bu_isciii/scratch.py
- bu_isciii/utils.py
Created module to revert copy to scratch, fixed som argument names, created some chice options for scratch copy.
> Created module to revert copy to scratch and fixed som argument names

- bu_isciii/conf/configuration.json
- bu_isciii/config_json.py
Configuration file defined under conf folder and code to read the json configuration
> Configuration Json file and config json reader

- bu_isciii/__main__.py
- bu_isciii/list.py
> List.py added to main

- bu_isciii/__main__.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/drylab_api.py
- bu_isciii/service_json.py
New module for handling bioinfo_doc was started.
Changing the type of error handing in the exception to Connection error.
> Create Module for bioinfo_doc, and corrected exception error type in drylab_api

- bu_isciii/deliver.py
> Generating HTML correctly

- bu_isciii/__main__.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/conf/configuration.json
Json configuration file was changed due to small bugs.
Documentation was added a selection to  choose the type of document to create
> Update configuration.json and created option to select the type of documentation

- bu_isciii/__main__.py
- bu_isciii/clean.py
- bu_isciii/conf/configuration.json
- bu_isciii/new_service.py
- bu_isciii/scratch.py
- bu_isciii/service_json.py
- bu_isciii/utils.py
Closes #62 and #60 
Besides 
- Variable names have been normalized and some code refactoring!
- Coverted new service get_services_ids method to function in utils
- Fixed variable name in ServiceJson.
- Some re-factoring in services.json
- Changed prompt_direction_selection function in scratch for generic prompt_selection
> Clean module linked in main, working with a wrapper function to choose with selection :smile_cat: 

- bu_isciii/__main__.py
- bu_isciii/list.py
> Improvements in service listing and include argument for find services in main

- bu_isciii/drylab_api.py
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/01-preproQC/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/02-preprocessing/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/03-procQC/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS02_MET/99-stats/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS02_MET/lablog
- bu_isciii/templates/IRMA/ANALYSIS/lablog
- bu_isciii/templates/IRMA/DOC/README
- bu_isciii/templates/IRMA/RAW/README
- bu_isciii/templates/IRMA/REFERENCES/README
- bu_isciii/templates/IRMA/RESULTS/README
- bu_isciii/templates/IRMA/TMP/README
- bu_isciii/templates/viralrecon/ANALYSIS/_02_create_run_percentage_Ns.sh
- bu_isciii/templates/viralrecon/ANALYSIS/lablog
- Added IRMA template
- Added new features to viralrecon template
> Updated templates with IRMA and fixed viralreon

- bu_isciii/templates/viralrecon/ANALYSIS/deduplicate_long_table.sh
- bu_isciii/templates/viralrecon/ANALYSIS/lablog
- bu_isciii/templates/viralrecon/RESULTS/lablog
- Added steps to deduplicate long table csv files
- Added a lablog to results folder as template for delivery
> Updated templates

- .github/workflows/python_lint.yml
- bu_isciii/__main__.py
- bu_isciii/conf/configuration.json
- bu_isciii/scratch.py
1. Fixed scratch copy command
- Fixed API configuration
- Removed one unnecessary variable
- Fixed scratch cleaning that was removing one file that was beng read
2. Fixed linting
- Fixed flake8 version
- Ignored some errors
- Added some black jupyer installation as for relecov platform
3. Fixed some typos and style from main script.
> Fixed scratch copy, linting and more

- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/lablog
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS02_MET/lablog
- bu_isciii/templates/IRMA/DOC/mag.config
- bu_isciii/templates/IRMA/RESULTS/lablog
- Updated new files generation according to request
- Updated MAG DSL2 version
> Updated IRMA template

- bu_isciii/clean.py
- bu_isciii/templates/services.json
- bu_isciii/utils.py
Fixed clean module:
1. Fixed get_service_ids when all was selected
2. Only purge folders/files when string is not empty, it gave an error
3. Added a function to remove work folder if exist
4. Removed work folder from service json because now there's a module to remove it
> Fixed Clean module

- bu_isciii/__main__.py
- bu_isciii/copy_sftp.py
- bu_isciii/templates/services.json
1. Added copy_sftp module to main
2. Updated copy SFTP description
3. catched RsyncError
4. Added test if service folder is inside de source path
5. Added final folder to service json to test if rsync worked with `ls`
6. Added log file in source folder to reads rsync command
> Updated Copysftp module

- bu_isciii/templates/assembly/ANALYSIS/ANALYSIS01_ASSEMBLY/lablog
- bu_isciii/templates/mtbseq/ANALYSIS/ANALYSIS01_MTBSEQ/01-preprocessing/lablog
- bu_isciii/templates/mtbseq/ANALYSIS/ANALYSIS01_MTBSEQ/02-kmerfinder/lablog
- bu_isciii/templates/mtbseq/ANALYSIS/ANALYSIS01_MTBSEQ/03-MTBSeq/lablog
- bu_isciii/templates/mtbseq_assembly/ANALYSIS/ANALYSIS01_MTBSEQ/05-MTBSeq/lablog
- bu_isciii/templates/mtbseq_assembly/ANALYSIS/ANALYSIS01_MTBSEQ/lablog
- bu_isciii/templates/pikavirus/ANALYSIS/ANALYSIS01_PIKAVIRUS/lablog
- bu_isciii/templates/pikavirus/ANALYSIS/lablog
- bu_isciii/templates/pikavirus/DOC/hpc_slurm_pikavirus.config
- bu_isciii/templates/plasmidid_assembly/ANALYSIS/ANALYSIS01_ASSEMBLY/lablog
- bu_isciii/templates/plasmidid_assembly/ANALYSIS/ANALYSIS02_PLASMIDID/lablog
- bu_isciii/templates/services.json
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/01-fastqc/lablog
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/02-preprocessing/lablog
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/03-preprocQC/lablog
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/04-snippy/lablog
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/05-iqtree/lablog
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/99-stats/lablog
- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/lablog
I have finished, tested, and saved the snippy full pipeline! If there's something missing, I'll check it out!
Also, I have added the PikaVirus template that was missing
> SNIPPY & PikaVirus templates ready!

- bu_isciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/02-preprocessing/lablog
This should fulfill the request!
> Changed trimmomatic for fastp in snippy template

- bu_isciii/templates/seek_and_destroy/ANALYSIS/ANALYSIS01_SEEK_DESTROY/lablog
- bu_isciii/templates/seek_and_destroy/ANALYSIS/lablog
- bu_isciii/templates/seek_and_destroy/DOC/README
- bu_isciii/templates/seek_and_destroy/DOC/seek_destroy.config
- bu_isciii/templates/seek_and_destroy/RAW/README
- bu_isciii/templates/seek_and_destroy/REFERENCES/README
- bu_isciii/templates/seek_and_destroy/RESULTS/README
- bu_isciii/templates/seek_and_destroy/TMP/README
- bu_isciii/templates/services.json
This should finish issue #116!
Nothing much to add, it was a simple task (as expected)!
> Seek and Destroy now implemented as a template

- bu_isciii/__main__.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/clean.py
- bu_isciii/conf/configuration.json
- bu_isciii/copy_sftp.py
- bu_isciii/drylab_api.py
- bu_isciii/new_service.py
- bu_isciii/scratch.py
1. Fixed API request to new format
2. Fixed service path, to be obtained from user info upon API request
3. Fixed finish module. Now does:
1. Clean /data/bi/scratch_tmp/bi/<service_folder>
2. Copy /data/bi/scratch_tmp/bi/<service_folder> to /data/bi/service_and_collaborations/*/*/<service_folder>
3. Rename folders in /data/bi/service_and_collaborations/*/*/<service_folder>
4. Copy /data/bi/service_and_collaborations/*/*/<service_folder> to SFTP folder
5. Fixed variable names to be uniform among all modules
6. Removed some redundant variables
Commands to make this run:
```
bu-isciii new-service SRVCNM707.1
bu-isciii bioinfo-doc SRVCNM707.1 #service_info
bu-isciii scratch --direction Service_to_scratch SRVCNM707.1
bu-isciii finish -t /data/bi/scratch_tmp/bi/ -s /data/bi/sftp/Labvirusres/ …
```
> Created branch for iskylims.isciiides changes

- bu_isciii/bioinfo_doc.py
- bu_isciii/drylab_api.py
- bu_isciii/new_service.py
- Added put for in progress in new-service
- Added put for delivery in bioinfo-doc
- Added test for samples in service and symbolic links
- Fixed some variable names
- Fixed some errors.
> Added put for in_progress and delivery and fixed some errors

- bu_isciii/__main__.py
- bu_isciii/archive.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/copy_sftp.py
- bu_isciii/new_service.py
- Added function in new-service to create samples json file
- Fixed some variable names in bioinfo_doc module
> Create samples json and fixed some variables

- bu_isciii/clean.py
- Now finds more than one work folder.
> Fixed work folders search

- bu_isciii/__main__.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/conf/configuration.json
- bu_isciii/drylab_api.py
- bu_isciii/utils.py
- Changed `year` to create service folder in `bioinfo_doc`: Now it takes service date and not resolution date (TODO: change in develop too)
- Added funtion to obtain SFTP folder name from user-json in bioinfo_doc module too.
- Added functions to POST delivery information in the API
- Added test that checks if delivery information already exist for the resolution:
- If exist: Ask if the users wants to post new delivery:
- If YES: POST new delivery information (TODO: Not post, but overwrite!!!)
- If not: continue
- If does not exist, POST new delivery information
> Multiple changes

- bu_isciii/__main__.py
- bu_isciii/archive.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/clean.py
- bu_isciii/copy_sftp.py
- bu_isciii/drylab_api.py
- bu_isciii/new_service.py
- bu_isciii/scratch.py
- bu_isciii/utils.py
- Added option to pass API password through command line
- Added option to pass API password through prompt
> Added API password options

- bu_isciii/clean.py
- bu_isciii/conf/configuration.json
- bu_isciii/copy_sftp.py
- bu_isciii/new_service.py
- bu_isciii/scratch.py
- bu_isciii/utils.py
- Created function get_service_path in utils
- Removed get_service_path function from modules and use the one in utils
- Fixed config.json indentation
> Removed get_service_path redundancies

- bu_isciii/bioinfo_doc.py
- bu_isciii/templates/jinja_template_delivery.j2
- Added delivery info to the jinja template
- Fixed delivery already existing test
- Removed pipelines in delivery from delivery json, now its not mandatory
> Added all delivery info

- bu_isciii/__main__.py
- bu_isciii/archive.py
- bu_isciii/drylab_api.py
- bu_isciii/utils.py
Here you have all the changes I have made for the archive module so far
> Archive module update

- bu_isciii/__main__.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/clean.py
- bu_isciii/conf/configuration.json
- bu_isciii/copy_sftp.py
- bu_isciii/drylab_api.py
- bu_isciii/new_service.py
- bu_isciii/scratch.py
- bu_isciii/templates/email.j2
- bu_isciii/utils.py
Added module to:
- Create e-mail html
- Add report PDF file
- Ask for additional CC for the e-mail
- Print or send e-mail
> Created e-mail send module

- bu_isciii/templates/wgstrio/ANALYSIS/ANALYSIS01_GENOME/03-annotation/lablog
mostly a QOL change so that we dont bump processes
> node management, minor change

- README.md
- bu_isciii/__main__.py
- bu_isciii/bioinfo_doc.py
- bu_isciii/new_service.py
- bu_isciii/scratch.py
- bu_isciii/templates/jinja_template_delivery.j2
- bu_isciii/templates/jinja_template_service_info.j2
- bu_isciii/templates/services.json
- bu_isciii/utils.py
- Fixed variables capitalization
- Fixed some functions due to version update
- Added option to generate PDF report without delivery and/or results markdowns
- Fixed report path
- Updated README
TODO:
- Fix e-mail sending
> Fixed bioinfo-doc module

- bu_isciii/templates/exomeeb/ANALYSIS/ANALYSIS01_EXOME/03-annotation/lablog
- bu_isciii/templates/exomeeb/ANALYSIS/ANALYSIS01_EXOME/lablog
- bu_isciii/templates/mtbseq/ANALYSIS/ANALYSIS01_MTBSEQ/03-MTBSeq/lablog
- bu_isciii/templates/services.json
Included mkdir logs and changed node partition to middle_idx in bu_isciii/templates/mtbseq/ANALYSIS/ANALYSIS01_MTBSEQ/03-MTBSeq/lablog 
Also sent exomiser process to background in bu_isciii/templates/exomeeb/ANALYSIS/ANALYSIS01_EXOME/03-annotation/lablog, included creationg of family.ped in bu_isciii/templates/exomeeb/ANALYSIS/ANALYSIS01_EXOME/lablog and removed {sample_name} from folders that are selected to be purged in bu_isciii/templates/services.json
> Small changes to exomeeb and mtbseq templates

- .github/workflows/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Created files for:
- Change log (CHANGELOG.md)
- Pull request template (PULL_REQUEST_TEMPLATE.md)
> Added changelog and pull request template

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/update_branches.yml
- CHANGELOG.md
- Contributing guidelines are now described for this repo
- New github action to automatically create PRs to syncronize branches
> Added contribution and github action files

- CHANGELOG.md
I included the changes from one of the last PR's to the `CHANGELOG.md` file in order to keep them tracked
> Updated CHANGELOG.md with last PR

- CHANGELOG.md
- bu_isciii/__main__.py
- setup.py
- Updated changelog
- Bumped new version
> Bump new version 1.0.1

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PULL_REQUEST_TEMPLATE.md
- .github/workflows/update_branches.yml
- CHANGELOG.md
- bu_isciii/__main__.py
- bu_isciii/autoclean_sftp.py
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/create_irma_stats.sh
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/lablog
- bu_isciii/templates/IRMA/RESULTS/irma_results
- bu_isciii/templates/assembly/ANALYSIS/ANALYSIS01_ASSEMBLY/lablog
- bu_isciii/templates/assembly/ANALYSIS/lablog_assembly
- bu_isciii/templates/assembly/DOC/hpc_slurm_assembly.config
- bu_isciii/templates/assembly/RESULTS/lablog_assembly_results
- bu_isciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/03-annotation/exomiser_configfile.yml
- bu_isciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/03-annotation/lablog
- bu_isciii/templates/services.json
- bu_isciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
- bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
- bu_isciii/templates/viralrecon/RESULTS/excel_generator.py
- bu_isciii/templates/viralrecon/RESULTS/viralrecon_results
- setup.py
Code contributions to the hotfix:
- [Pablo Mata](https://github.com/Shettland)
- [Jaime Ozaez](https://github.com/jaimeozaez)
- [Sara Monzón](https://github.com/saramonzon)
- [Sarai Varona](https://github.com/svarona)
- [Daniel Valle](https://github.com/Daniel-VM)
- Added new line in `buisciii_tools/bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon`, in order to automatically rename `ANALYSIS0X_MAG` directory with the current date. 
- Introduced handling of flu-C in `buisciii_tools/bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/` `lablog` and `create_irma_stats.sh`
- Small changes to `buisciii_tools/bu_isciii/templates/viralrecon/RESULTS/viralrecon_results` for blast and new excel_generator.py
- Introduced better error handling in excel_generator.py. Now it can also …
> New version 1.0.1

- CHANGELOG.md
- bu_isciii/archive.py
- setup.py
> Prepare Release 2.0.0

- CHANGELOG.md
- bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/01-preprocessing/lablog
- bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/02-ariba/run/lablog
- bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/02-ariba/summary/lablog
Fixed multiple things in characterization template:
- Fixed path to trimmed reads from bacass
- Removed irrelevant comments
> Fixed characterization template

- bu_isciii/templates/services.json
Updated _services.json_ to include the paths to the assembly markdowns (_delivery_md and results_md_).
> Updated services.json

- CHANGELOG.md
- bu_isciii/conf/configuration.json
> Changed scratch-copy default queue in configuration.json

- bu_isciii/assets/reports/results/exomeeb.md
- bu_isciii/assets/reports/results/trios.md
> Included annotated tab description in exome-trios markdowns

- CHANGELOG.md
- bu_isciii/templates/exomeeb/ANALYSIS/ANALYSIS01_EXOME/lablog
- bu_isciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/lablog
- bu_isciii/templates/wgstrio/ANALYSIS/ANALYSIS01_GENOME/lablog
> Updated sarek version where needed

- CHANGELOG.md
- README.md
- bu_isciii/bioinfo_doc.py
- bu_isciii/conf/configuration.json
- bu_isciii/conf/configuration_dev.json
- environment.yml
> Removed ad hoc path for wkhtmlpdf and better catching error

- CHANGELOG.md
- bu_isciii/bioinfo_doc.py
> Modified bioinfo_doc.py so that new lines are applied when creating the .pdf file

- bu_isciii/clean.py
> Fixed error because items can be none, empty list, or list with content

- CHANGELOG.md
- bu_isciii/templates/assembly/DOC/hpc_slurm_assembly.config
- bu_isciii/templates/mtbseq/ANALYSIS/ANALYSIS01_MTBSEQ/03-MTBSeq/lablog
- bu_isciii/templates/services.json
- bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
**This PR closes #283, #297 and #298. Furthermore, a small issue related to assembly's config file is solved, since the `MULTIQC` process was changed to `MULTIQC_CUSTOM`.**
> Updated some templates

- CHANGELOG.md
- bu_isciii/templates/mag/ANALYSIS/ANALYSIS02_MAG/99-stats/lablog
Fixed 99-stats (MAG) symlinks creation.
> Fixed 99-stats (MAG) symlinks creation

- CHANGELOG.md
- bu_isciii/bioinfo_doc.py
> Modified bioinfo_doc.py to apply new lines in the email

- CHANGELOG.md
- bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
- Create a log file for all the echo's and output generated when running the lablog.
- Create a log file by adding a --output argument for the following command:
```
srun --partition short_idx singularity run -B ${PWD} /data/bi/pipelines/singularity-images/$latest_version_pangolin pangolin --update-data --datadir ${PWD}/$(date '+%Y%m%d')/
```
- Check if previous command performed correctly (by checking exit 0 or exit 1 in slurm last job / or by checking the newly created log), and then, adjust the message "Pangolin database UPDATED."
- Check and adjust (when neccesary) the rest of "something finished/downloaded correctly" messages (even the last one!).
- Enabled module load singularity inside the script.
- Modified check_references function in order to be able to find every reference (not …
> Several improvements for lablog_viralrecon

- CHANGELOG.md
- bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/create_irma_vcf.py
> Created python to generate IRMA vcf file

- CHANGELOG.md
- bu_isciii/templates/sftp_user.json
> Added mvmoneo to SFTP users

- CHANGELOG.md
- bu_isciii/__main__.py
- bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/05-mlva/lablog
- bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/99-stats/lablog
- bu_isciii/templates/characterization/REFERENCES/lablog
- bu_isciii/templates/mag/ANALYSIS/ANALYSIS02_MAG_TAXONOMICS/lablog
- bu_isciii/templates/rnaseq/ANALYSIS/DATE_ANALYSIS01_RNASEQ/lablog
- bu_isciii/templates/viralrecon/ANALYSIS/remove_columns_mapping_table.sh
- bu_isciii/templates/viralrecon/DOC/viralrecon_no_host_reads.config
- bu_isciii/templates/viralrecon/DOC/viralrecon_params.yml
- bu_isciii/utils.py
**This PR addresses #312, #313, #314, #315, #322, #323, #324, #327, #328 and #329.**
> Updated several templates

- CHANGELOG.md
- bu_isciii/__main__.py
- setup.py
> Updated CHANGELOG.md, setup.py and __main__.py for the new release

- CHANGELOG.md
- bu_isciii/conf/configuration.json
> fix archived path

- CHANGELOG.md
- bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/03-amrfinderplus/lablog
Added the generation of a second script that processes the tsv generated by amrfinderplus into a new complete tsv.
> Updated 03-amrfinderplus lablog (characterization template)

- CHANGELOG.md
- bu_isciii/templates/viralrecon/ANALYSIS/lablog_bam2fq
- bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
- bu_isciii/templates/viralrecon/ANALYSIS/remove_columns_mapping_table.sh
> Created lablog_bam2fq and updated some files from viralrecon's template

- CHANGELOG.md
- buisciii/templates/IRMA/DOC/irma_config.sh
- buisciii/templates/IRMA/RESULTS/lablog_irma_results
- Modified field (cut) where extracted flu type information in lablog_irma_results.
- Modified path for temporal files in irma_config.sh.
Closes #415 #416 
> Fixing some issues in IRMA template

- CHANGELOG.md
- buisciii/templates/chewbbaca/ANALYSIS/ANALYSIS01_CHEWBBACA/02-chewbbaca/lablog
- buisciii/templates/chewbbaca/REFERENCES/lablog
- buisciii/templates/chewbbaca/RESULTS/lablog_mlst_results
> Fixed minor mistakes in ChewBBACA's template

- CHANGELOG.md
- buisciii/drylab_api.py
> Fixed error message when resolution ID does not exist

- CHANGELOG.md
- buisciii/__main__.py
- pyproject.toml
`CHANGELOG.md`, `pyproject.toml` and `__main__.py` are updated to display the 2.2.6 version upon the next release of the BU-ISCIII tools.
> Pre-release v2.2.6

- CHANGELOG.md
- buisciii/templates/services.json
Updated `services.json` file in order to properly delete folders and files when running clean module.
Closes #417 #419 #431 
> Review of folders and files to delete in `services.json`

- buisciii/templates/viralrecon/RAW/lablog_bam2fq
Fixed script logic: prevent overwriting in loop.
> Fixed script for prevent overwriting in loop

- CHANGELOG.md
- buisciii/templates/sftp_user.json
Added new user: `e.abascal` to `sftp_users.json`
> Add new user to `sftp_user.json`

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/get_percentage_LDM.py
Update sample handling in templates/viralrecon/ANALYSIS/get_percentage_LDM to handle identificator as string. 
> Update sample handling in get_percentage_LDM

- CHANGELOG.md
- buisciii/templates/pikavirus/ANALYSIS/ANALYSIS01_PIKAVIRUS/lablog
Added a small script for results filtering in pikavirus template.
> Added _02_filter_results.sh script to pikavirus template

- CHANGELOG.md
- buisciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/lablog
This PR updates the `exometrio lablog` to support processing data for a fourth individual in the `family.ped` file.
> Update `exometrio lablog` to Handle Fourth Individual

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
- buisciii/templates/viralrecon/DOC/viralrecon.config
Fixed ivar version in viralrecon to fix error processing IonTorrent variants.
Fixed summary report for single_end data
> Updated code for IonTorrent

- CHANGELOG.md
> Added contributor

- CHANGELOG.md
- buisciii/bioinfo_doc.py
- buisciii/templates/email.j2
- Refactored `Bioinfo-doc` to internalize the logic for handling email attachments.
- Added a prompt to allow users to attach additional files (e.g., `.xlsx`, `.docx`, etc.) when sending delivery emails.
- Updated `send_email()` method to support multiple attachments, keeping the main `results.pdf` file separate from user-provided files.
- Ensured backward compatibility for users not providing extra attachments.
- Increased the width of the email body for better display on desktop clients (from 600px to 1000px).
- Changed the logo source.
- Prompt during email sending asking if the user wants to add additional attachments.
- Files are provided as absolute paths separated by semicolons (`;`) during interaction.
- Graceful handling of invalid file paths with warnings.
- Modular and …
> Add support for attaching additional files in email delivery

- CHANGELOG.md
- buisciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/04-snippy/lablog
New masking system using a modified snippy script.
Explained here: 
https://github.com/tseemann/snippy/issues/268#issuecomment-2804520905
> Update snippy template

- CHANGELOG.md
- buisciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/99-stats/lablog
Avoided error messages when running 99-stats lablog several times (snippy template)
> Avoided error messages when running 99-stats lablog several times (snippy template)

- CHANGELOG.md
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog
Flu type is added into the summary_stats file from the IRMA template. Flu subtype is also displayed in a separate column.
> Added flu_type to summary_stats (IRMA template)

- CHANGELOG.md
- buisciii/__main__.py
- pyproject.toml
`CHANGELOG.md`, `__main__.py` and `pyproject.toml` are updated for the release of the 2.2.8 version of the buisciii-tools.
> Pre-release v2.2.8

- CHANGELOG.md
Reverted changes in CHANGELOG.md in order to finish de new release.
> Updated CHANGELOG.md for new release

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
> Updated create_summary_report.sh to handle properly single end reads

- CHANGELOG.md
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/lablog_versions
> Updated IRMA's template to obtain software versions

- CHANGELOG.md
- buisciii/__main__.py
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog
- pyproject.toml
Apart from preparing for the new release, this PR closes #517.
> Pre-release v2.2.9

- CHANGELOG.md
- buisciii/__main__.py
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/06-variant-calling/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/lablog_versions
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
- buisciii/templates/viralrecon/RAW/lablog_bam2fq
- pyproject.toml
> Develop merge for 2.2.9 release

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
> Redefinition of analysis_date and lineage_analysis_date based on mapping folder and DOC config in viralrecon's template

- CHANGELOG.md
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/merge_results.py
- buisciii/templates/IRMA/RESULTS/lablog_irma_results
> Improved Nextclade's individual results aggregation and updated lablog_irma_results to create new symlinks

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
> Adapted create_summary_report.sh to handle multiple references and add lineage columns to pangolin .csv only if they do not exist yet

- CHANGELOG.md
- buisciii/__main__.py
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/lablog
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/05-nextclade/merge_results.py
- buisciii/templates/IRMA/RESULTS/lablog_irma_results
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
- pyproject.toml
> Develop merge for 2.2.10 release

- CHANGELOG.md
- buisciii/templates/pikavirus/DOC/hpc_slurm_pikavirus.config
> PikaVirus_dev_2.6 environment added to hpc_slurm_pikavirus.config

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
> Changed analysis_date to deal properly with dates from RSV services

- CHANGELOG.md
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
> Fixed the way whether samples are paired or single-end is detected

- CHANGELOG.md
- README.md
- buisciii/__main__.py
- buisciii/assets/utils/lablog_SRA_download
- buisciii/bioinfo_doc.py
- buisciii/clean.py
- buisciii/conf/configuration.json
- buisciii/scratch.py
- buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog
- buisciii/templates/pikavirus/DOC/hpc_slurm_pikavirus.config
- buisciii/templates/rnaseq/ANALYSIS/DATE_ANALYSIS01_RNASEQ/lablog
- buisciii/templates/rnaseq/RESULTS/lablog_rnaseq_results
- buisciii/templates/viralrecon/ANALYSIS/create_assembly_stats.R
- buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
- buisciii/templates/viralrecon/RESULTS/excel_generator.py
- pyproject.toml
> Develop merge for 2.2.11 release

- CHANGELOG.md
- buisciii/__main__.py
- pyproject.toml
This PR is done for the following v2.2.13 release of the buisciii-tools.
> Pre-release v2.2.13
