BU-ISCIII/buisciii-tools

bu_isciii/__main__.py, bu_isciii/new_service.py, templates/services.json
Created copy_template function so template folder can be copied to destination service folder. Temporarilly added hardcoded in the code the `service_template = ["viralrecon"]  ###TMP!!`
Also, magaed the possibility to call the json module:
```
```
=> Added function to copy template folders to service folder

README.md, bu_isciii/__main__.py, bu_isciii/autoclean_sftp.py, bu_isciii/sftp_autoclean.py
New module to remove the old services in the sftp:
- Finds all services listed in the sftp
- For each service determines the last modification/creation date by scanning all files stored in it
- Marks services older than 14 days (default: `-d 14`) as old-services
- Deletes old services from sftp
=> Sftp autoclean module

bu_isciii/__main__.py, bu_isciii/conf/configuration.json, bu_isciii/drylab_api.py, bu_isciii/new_service.py, bu_isciii/scratch.py, bu_isciii/utils.py
- Fixed API autentication
- Refactores some API variables updated in DB
- Fixed some utils
=> Multiple changes

bu_isciii/new_service.py, bu_isciii/utils.py
- Fixed get_service_paths function
- Fixed get_service_paths call in new_services
=> Fixed some API variables and errors

bu_isciii/bioinfo_doc.py, bu_isciii/clean.py, bu_isciii/new_service.py
-  Fix modules in which samples are involved. 
- Included appropriate warning messages when no samples are found.
- This should solve #110
=> Fix module's error when no samples are involved in service

bu_isciii/__main__.py, bu_isciii/archive.py, bu_isciii/bioinfo_doc.py, bu_isciii/clean.py, bu_isciii/conf/configuration.json, bu_isciii/copy_sftp.py, bu_isciii/drylab_api.py, bu_isciii/new_service.py, bu_isciii/scratch.py, bu_isciii/utils.py, requirements.txt
I introduced user and password credentials to authenticate the requests to iskylims API into all the modules.
The main differences are present in:
1. [__main__.py](https://github.com/BU-ISCIII/buisciii-tools/blob/develop/bu_isciii/__main__.py). Buisciii-tools can now be executed using a credentials file in yaml format in the user's home directory; or specify them before the command that is going to be passed to the Command line.
2. [utils.py](https://github.com/BU-ISCIII/buisciii-tools/blob/develop/bu_isciii/utils.py) Received three functions that aim to extract the fields from the yaml file and to verify that the extraction was correct.
The rest of the modules received minor changes such as error handling.
I also included the srun command into the scratch module so the copy process is …
=> Introduction of credentials as API authentication method

bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/create_irma_stats.sh, bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/lablog, bu_isciii/templates/IRMA/RESULTS/irma_results, bu_isciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/03-annotation/exomiser_configfile.yml, bu_isciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/03-annotation/lablog, bu_isciii/templates/viralrecon/RESULTS/excel_generator.py, bu_isciii/templates/viralrecon/RESULTS/viralrecon_results
Several changes were introduced for irma's `lablog` and `create_irma_stats.sh` in order to extract data from Influenza-C samples when present in service. Also some fixes and implementations in `viralrecon_results` and `excel_generator.py`
`PASS_ONLY` line was commented in exometrio's `exomiser_configfile.yml` and a deprecated line removing `spring.log` was deleted from `03-annotation/lablog` in this template
=> Introduced handling of Influenza-C in IRMA template and small fixes in viralrecon and exometrio

bu_isciii/autoclean_sftp.py, bu_isciii/templates/viralrecon/ANALYSIS/create_summary_report.sh, bu_isciii/templates/viralrecon/RESULTS/excel_generator.py
I renamed some variables in `create-summary_report` from viralrecon template as their name was misleading and fixed a small typo in regex finding in `excel_generator.py`
=> Small changes in variables names for create_summary_report and fix typo in excel_generator.py

.github/CONTRIBUTING.md, CHANGELOG.md, bu_isciii/templates/assembly/ANALYSIS/ANALYSIS01_ASSEMBLY/lablog, bu_isciii/templates/assembly/DOC/hpc_slurm_assembly.config, bu_isciii/templates/assembly/RESULTS/lablog_assembly_results
This PR introduces a new template for bacterial genome assembly, covering the assembly of genomes from short, hybrid, and long sequences using the[ nf-core bacass::bu-isciii-develop (forked) ](https://github.com/Daniel-VM/bacass/tree/buisciii-develop) workflow . Consequently, this template will replace the previous "assembly" template, expanding its functionality.
-  `Lablog_assembly`: Parses `fastq.gz` files, classifying them into short and long reads based on their filenames.
- `Lablog`: 1. Introduces a new colored prompt selection method.; 2. Sets up the sample sheet autonomously based on the user's assembly choice (short, long, hybrid).
- `Hpc_slurm_assembly.config`: Sets up the output folder using nf custom configuration files.
- `Lablog_assembly_results`: Adjusts file selection for …
=> New Bacterial Genome Assembly Template: Short, Long, and Hybrid Sequences

CHANGELOG.md, bu_isciii/templates/viralrecon/RESULTS/excel_generator.py
With these changes, instead of using an external parameter when executing, excel_generator.py will automatically try to merge pangolin and nextclade tables when more than 1 reference is found
=> Small changes in excel_generator.py

CHANGELOG.md, bu_isciii/conf/configuration.json, bu_isciii/scratch.py, bu_isciii/templates/services.json
I included several last minute changes to fix some bugs regarding the tools:
- Included IRMA template to services.json as it was not included
- Changed the URL from iskylims api to the new one (previously iskylims.isciiides.es)
- Changed how the service_info.txt is generated during scratch process to allow the script to work even thouhg srun returns exit_status 0 without waiting for the rsync command to finish properly. I will include an issue to handle this in a better way, but right now is functional.
=> Small update and bug fixing pre-release 2.0.0

CHANGELOG.md, bu_isciii/__main__.py, bu_isciii/bioinfo_doc.py, bu_isciii/templates/services.json
I included several changes into bioinfo-doc module:
- Email password can now be given in buisciii_config.yml file with the tag "email_password"
- There's a default CC now to receive our own reports to the bioinformatics institutional mail
- Delivery notes can be given using a plain text file, which will be asked via prompt
Also included the version 2.0.0 tag into `__main__.py` and blast_nt into `templates/services.json`
=> Bioinfo-doc updates: email password in yml and delivery notes in text file

CHANGELOG.md, bu_isciii/autoclean_sftp.py, bu_isciii/bioinfo_doc.py, bu_isciii/templates/sftp_user.json, bu_isciii/templates/viralrecon/RESULTS/excel_generator.py, bu_isciii/templates/viralrecon/RESULTS/viralrecon_results
=> Small fixes in autoclean_sftp and bioinfo-doc. Reverted excel_generator.py

CHANGELOG.md, bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/lablog, bu_isciii/templates/IRMA/RESULTS/irma_results, bu_isciii/templates/services.json, bu_isciii/templates/viralrecon/DOC/viralrecon_sars.config, bu_isciii/templates/viralrecon/RESULTS/viralrecon_results
I deleted empty strings `""` inside folders to clean from services.json that were leading to a complete deletion of all the folders in the service if any of those templates were selected. 
I also included a sed that was missing inside 04-irma/lablog's _03_post_processing.sh from IRMA template. Also included a line in RESULTS/lablog to create a summary of the different types of flu that were found inside irma_stats.txt
=> Empty string bug fix in services.json and 04-irma lablog

CHANGELOG.md, setup.py
=> Prepare release 2.1.0

CHANGELOG.md, bu_isciii/templates/assembly/RESULTS/lablog_assembly_results, bu_isciii/templates/mtbseq/RESULTS/lablog_mtbseq_results
Creation of a file that automates the creation of symbolic links for the main results files in the results directory.
Closes #232 
=> Creation of MTBseq lablog_results

.github/workflows/python_lint.yml, CHANGELOG.md, bu_isciii/conf/configuration.json, bu_isciii/templates/exometrio/ANALYSIS/ANALYSIS01_EXOME/03-annotation/lablog, bu_isciii/templates/rnaseq/ANALYSIS/DATE_ANALYSIS01_RNASEQ/lablog
- Closes #235
- Closes #228
- Closes #196  
=> Template issues

CHANGELOG.md, bu_isciii/templates/viralrecon/RESULTS/lablog_viralrecon_results
The extension file of all_samples_virus_table_filtered has been changed from csv to tsv so that the symbolic link pointing pikavirus result table is properly created using lablog_viralrecon_results. 
=> Extenison file (csv to tsv) in lablog_viralrecon_results to match pikavirus table

.github/workflows/python_lint.yml, CHANGELOG.md, README.md, bu_isciii/scratch.py
=> Actions changes to force python lint to success if no .py files are in PR

CHANGELOG.md, bu_isciii/__main__.py, bu_isciii/clean.py, bu_isciii/templates/services.json
Fixed clean module:
- Corrected purge_files function. Now it is able to properly find and remove the files set in services.json for every service.
-  Renaming stage moved from clean to rename_nocopy option in order to avoid non-renamed folders being copied from services_and_colaborations to sftp.
- Updated services.json file with correct file paths and file names for some services.
Closes #199 
Closes #221 
Closes #233 
Related #223
=> Fixed clean module

CHANGELOG.md, bu_isciii/__main__.py, tatus
Restored proper performance of autoclean-sftp funcion by adding @click.pass_context before the function in __main__.py file.
=> Fixed autoclean-sftp function

CHANGELOG.md, bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon, tatus
Fixed singularity-images path when updating pangolin database in lablog_viralrecon.
Added line break after prompted input.
=> Fixed singularity-images path when updating pangolin database in lablog_viralrecon.

CHANGELOG.md, bu_isciii/templates/lowfreq_panel/RESULTS/lablog_lowfreq_panel_results, bu_isciii/templates/mtbseq_assembly/RESULTS/lablog_mtbseq_assembly_results, bu_isciii/templates/rnaseq/RESULTS/lablog_rnaseq_results, bu_isciii/templates/viralrecon/RESULTS/lablog_viralrecon_results
=> Created RESULTS/lablog files where needed to include multiqc_report.html

CHANGELOG.md, bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
This PR changes a part of viralrecon's lablog file so that it looks for references within refgenie's system and, in case a reference file has not been downloaded yet, this file is downloaded and stored appropriately.
=> Changed viralrecon's lablog so that references are available within refgenie

CHANGELOG.md, bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/04-emmtyper/lablog, bu_isciii/templates/characterization/RESULTS/lablog_characterization_results, bu_isciii/templates/services.json
Added a lablog that generates all required bash and SLURM scripts to perform the characterization of genes encoding the protein emm with [emmtyper](https://github.com/MDU-PHL/emmtyper):
0. Jobarray to uncompress assemblies (*.fasta.gz) from assembly template.
1. Slurm script to perform emmtyper analysis.
ALL. Script to run both 0,1
(singularity dependency added)
=> Added new tool,emmtyper, into `characterization` template

CHANGELOG.md, bu_isciii/templates/IRMA/ANALYSIS/ANALYSIS01_FLU_IRMA/04-irma/lablog
So far, when launching IRMA's lablog, the sequences corresponding to the samples associated with each influenza type were displayed within the .txt files of each type several times, and the same thing happened in all_samples_completo.txt. This is fixed with this PR.
=> Fixed IRMA's lablog so that sequences are not displayed several times

CHANGELOG.md, bu_isciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
Lablog viralrecon tries to identify to which family all new references to be downloaded belong. If the reference does not belong to any family, it fails.
Now, references that do not belong to any family are stored in "miscellaneous" folder.
=> Lablog_viralrecon is now able to download references from ncbi that don't belong to any family

CHANGELOG.md, bu_isciii/templates/rnaseq/ANALYSIS/DATE_ANALYSIS01_RNASEQ/02-differential_expression/differential_expression.R, bu_isciii/templates/rnaseq/ANALYSIS/DATE_ANALYSIS01_RNASEQ/02-differential_expression/time_series_differential_expression.R, bu_isciii/templates/sftp_user.json
Multiple script fixes:
- Fixed error for DET when generating pheatmap
- Updated filename for tx2gene file, that has been renamed in nf-core pipeline
- Added timeseries experiment script.
=> Updated RNAseq DE scripts

CHANGELOG.md, bu_isciii/templates/services.json
Updated the rest of pipelines configuration in services.json for proper cleaning of folders and files.
Closes #223 
=> Review and update of services.json for files and folders cleaning

CHANGELOG.md, bu_isciii/bioinfo_doc.py, bu_isciii/templates/jinja_template_delivery.j2, bu_isciii/templates/services.json
This PR addresses **#219**. 
**Explanation of the changes**:
**Three files** have been modified in this PR:
1. **`services.json`**: all labels corresponding to their respective pipelines have been included in `services.json`.
2. **`bioinfo_doc.py`**:
* A new `load_versions(self)` function has been created, which looks for all `versions.yml` files associated to a certain service, extracts the absolute path of each one of these files and creates a dictionary, in which each path is associated to its content. This function also takes into consideration whether a versions.yml is identical to another one that has been already read, so that this info is not displayed in the .pdf file several times (this can be useful, for example, in the case of …
=> Updated bioinfo_doc.py, jinja_template_delivery.j2 and services.json to include versions.yml in the delivery .pdf

CHANGELOG.md, bu_isciii/templates/mag/ANALYSIS/ANALYSIS02_MAG_TAXONOMICS/lablog, bu_isciii/templates/mag/ANALYSIS/ANALYSIS03_MAG_ALL/lablog, bu_isciii/templates/sftp_user.json, bu_isciii/utils.py
**This PR addresses #333**. Furthermore, some small modifications have been added to the `get_md5()` function in `utils.py`. `sftp_user.json` has also been updated.
=> Updated MAG lablogs and utils.py

CHANGELOG.md, README.md, bu_isciii/__main__.py, bu_isciii/bioinfo_doc.py, bu_isciii/templates/viralrecon/ANALYSIS/remove_columns_mapping_table.sh, setup.py
This PR adds some final improvements to the code before the release of the 2.2.0 version of the BU-ISCIII tools.
=> Updated some files for the 2.2.0 release

CHANGELOG.md, bu_isciii/templates/characterization/ANALYSIS/ANALYSIS01_CHARACTERIZATION/04-emmtyper/lablog
Minor fixes and updates of the characterization template: emmtyper section.
- Fixed path to database.
- updated emmtyper params.
=> Emmtyper characterization template - Fixed path to blast database and update  params

.github/workflows/pypi_publish.yml, CHANGELOG.md, README.md
=> Included actions to publish releases to pypi

CHANGELOG.md, bu_isciii/new_service.py, bu_isciii/templates/assembly/DOC/hpc_slurm_assembly.config, bu_isciii/templates/sftp_user.json
This PR addresses #361 and #362.
=> Updated sftp_user.json and some templates

CHANGELOG.md, bu_isciii/new_service.py
Fixed code to properly handle a service without samples. Fixed issue #371 
=> Fixed code to properly handle a service withut samples

CHANGELOG.md, bu_isciii/templates/sftp_user.json
Add pberzosa to SFTP along with his lab directory
=> Add user to sftp_user.json

CHANGELOG.md, buisciii/templates/services.json
Fixed copy sftp bug by adding last_folder field to plasmidid_assembly service in services.json.
Closes #429 
=> Fixed copy-sftp bug

CHANGELOG.md, buisciii/bioinfo_doc.py
When trying to overwrite delivery notes while running bioinfo-doc (or resuming after aborting), the script crashes because the attribute self.provided_text is not defined.
This bug has been fixed by adding a step to check if self.provided_text is defined.
Closes #215 
=> Fixed bioinfo-doc resume function

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
Fixed bug when running `_08_create_quality_control_summary.sh`.
Closes #446 
=> Solved `_08_create_quality_control_summary.sh` bug in viralrecon template

CHANGELOG.md, buisciii/__init__.py, buisciii/assets/outbreakinfo/get_mutations_outbreak_info.R, buisciii/assets/outbreakinfo/lablog, buisciii/assets/outbreakinfo/update_lineage_data.py
This PR adds the necessary lablog and scripts to the assets directory for updating the list of lineage-defining mutations and managing its version control.
**Changes:**
- Uploaded lablog detailing the update process.
- Added scripts to automate the update of lineage-defining mutations.
- Implemented version control mechanisms to track changes over time.
=> Add `assets` for Updating Lineage-Defining Mutations from `outbreak-info`

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/get_percentage_LDM.py
This PR updates `get_percentage_LDM.py` to reference the latest version of the CSV file, which is updated whenever `pango-designation` assigns a new tag.
=> Fix `get_percentage_LDM.py` to Use Versioned CSV File

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/lablog_bam2fq, buisciii/templates/viralrecon/RAW/lablog_bam2fq
This PR **moves `lablog_bam2fq.sh` to `RAW/`**, corrects **path and regex errors**, and ensures that the **BAM-to-FASTQ pipeline functions correctly**.  
Additionally, it adapts the `_01_bam2fq.sh` and `_02_pgzip.sh` scripts and introduces a new `_03_symlink.sh` to **create symbolic links in `ANALYSIS/00-reads/`**.
- Ensures all BAM-to-FASTQ processing happens inside `RAW/`.
- Prevents issues caused by working in `ANALYSIS/`.
- Adjusted directory handling to prevent incorrect relative paths.
- Improved BAM file name parsing to avoid incorrect sample extraction.
- `_01_bam2fq.sh` now correctly detects **all BAM files** in `RAW/`.
- `_02_pgzip.sh` ensures **compression of FASTQ files** and removes uncompressed files.
- Automatically removes **broken links before recreating them**.
- Ensures …
=> Move lablog_bam2fq.sh to RAW/ & Fix Path Issues

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
- Modified the way lablog_viralrecon updates references.txt file in order to speed this process.
- Fixed wrong path to gff files when new references cannot be downloaded from ncbi.
- Added exiting stage when refgenie environment fails to load.
Closes #454 #456 #457 
=> Some fixes and enhancements for lablog_viralrecon

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/get_percentage_LDM.py
This change allows that when reading the `s_gene_combined_metrics.tsv` file the `sample` column is processed as a `string`.
=> Update `get_percentage_LDM.py` to read `sample` column as string

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/get_percentage_LDM.py
This PR updates the `get_percentage_LDM.py` script to correctly handle cases where no lineage is found at the `outbreak.info` CSV level.
**Changes:**
- Added a check to detect when the lineage column is empty or missing in the input CSV.
- The script now assigns `"Not Evaluable [NCIT:C186292]"` to `%LDMutations` in these cases.
- Prevents crashes or misleading 0% values when no lineage is available for comparison.
=> Update `get_percentage_LDM.py` to Handle Cases with `No Lineage Found` in outbreak.info CSV

CHANGELOG.md, buisciii/clean.py
Clean module has a bug when cleaning folders. Previously, when searching for folders to clean up, only the end of the folder name was matched ( the same applies to files), potentially leading to the unintentional deletion of folders and files.
For this reason, the way in which these folders and files are searched has been modified, making an exact match necessary to proceed with their cleaning.
Closes #462 
=> Modified clean.py in order to properly delete exact matching-name folders and files

CHANGELOG.md, buisciii/templates/email.j2
As described in the title, explicitly added “14 days” of permanence of the results in sftp folder to the e-mail sent to the users during service delivery.
Closes #475 
=> Added information on the period of permanence of the results in the sftp folder in email template

CHANGELOG.md, buisciii/templates/snippy/ANALYSIS/ANALYSIS01_SNIPPY/99-stats/lablog
As indicated in the title, added `sort -u` function to wgs_metrics_all.txt file generation command in 99-stats lablog in order to avoid inconsistencies in the order of the samples between the samples_id.txt file and the mapping_stats.txt file.
Closes #492 
=> Added sort -u to wgs_metrics_all.txt file generation command in 99-stats lablog (snippy template)

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/lablog_viralrecon
Version of ARTIC primers is outdated. Modified artic bed version in lablog_viralrecon for SARS-CoV-2 analysis.
Closes #504 
=> Modified artic bed version in lablog_viralrecon for SARS-CoV-2 analysis

CHANGELOG.md, buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/06-variant-calling/lablog
This PR fixes an issue in the `snpeff/snpsift` annotation step where VCF input files were not correctly resolved due to incorrect handling of relative paths.
=> Fix relative path handling in `snpeff/snpsift` annotation

CHANGELOG.md, buisciii/templates/viralrecon/RAW/lablog_bam2fq
Cut has been replaced with sed in order to replace `_R1.bam` in the bam files and so allow the creation of the variable sample for those sample ids having several underscores such as GISAID records (i.e. EPI_ISL_666) when relecov-tools are used. 
Sed has been added rather than any other options becuase pipeline_manager.py from relecov-tools adds the last part of the file name to the sequencing_sample_id 
`seq_r1_sample_id = sample["sequencing_sample_id"] + "_R1." + ext`
and it should work porperly without deeply changing the code. 
- If a new template was added make sure:
=> Added sed to lablog_bam2fq to allow proper creation of variable sample (i.e. EPI_ISL_111111)

CHANGELOG.md, buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog
This PR improves the robustness of the IRMA 99-stats lablog script by enforcing the presence of taxprofiler results before continuing with execution.
=> Update `IRMA 99-stats lablog` to raise error if taxprofiler results are missing

CHANGELOG.md, buisciii/templates/IRMA/ANALYSIS/ANALYSIS01_IRMA/99-stats/lablog, buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
* IRMA's 99-stats lablog file is updated to correct a wrong variable definition.
* Updated viralrecon's create_summary_report.sh to add clade's info into the mapping_illumina.tab file, apart from adding the lineage analysis date and the pango-data version into the pangolin .csv files.
=> Fixed variable definition in 99-stats lablog

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
This PR updates the `create_summary_report.sh` script from the ViralRecon template to ensure that the `analysis_date` and `lineage_assignment_date` column is consistently generated using the ISO 8601 date format (`YYYY-MM-DD`).
**Changes Introduced:**
- Enforces the `analysis_date` and `lineage_assignment_date` to always follow the `YYYY-MM-DD` format, regardless of system locale or date utility defaults.
=> Fix `analysis_date` and `lineage_assignment_date` format in `create_summary_report.sh`

CHANGELOG.md, buisciii/assets/utils/lablog_SRA_download
Sometimes, some assembly services that are requested to the Unit require downloading .fastq files from SRA, and this has to be done manually, which can be tedious when having to analyse multiple samples. This script automates this process, downloading the .fastq files for all the SRA entries indicated in samples_id.tx, and then renaming them so that they can be used properly for subsequent analyses.
=> Included new script to download multiple SRA entries in fastq format

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/create_summary_report.sh
As per the title, this PR is done so that the `create_summary_report.sh` script from viralrecon's template transforms negative values to 0.
=> Updated create_summary_report.sh to handle negative values

CHANGELOG.md, buisciii/templates/viralrecon/ANALYSIS/create_assembly_stats.R
As per the title, this PR updates the assembly stats script to handle files in RAW properly and when quast results are not available for any sample.
=> Updated assembly stats script to properly handle when quast results are not available

CHANGELOG.md, buisciii/bioinfo_doc.py, buisciii/scratch.py
This PR closes #547. Besides, the `scratch_tmp_dir` variable from scratch module is redefined so that data is copied properly to the corresponding route.
=> Fixed the bioinfo_doc module to properly ask for email text notes and the scratch module to use proper scratch_tmp_path

CHANGELOG.md, buisciii/templates/assembly/ANALYSIS/ANALYSIS01_ASSEMBLY/lablog, requirements.txt
1) Fix ModuleNotFoundError: No module named 'pkg_resources' during installation by installing setuptools in requirements
2) Update bacass version to 2.3.1
Problem
=> Fix `pkg_resources` installation error and update `bacass` version in `Assembly` template
